'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="WR_SenalesCaribe")>  _
Partial Public Class SecurityDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertUsuario(instance As Usuario)
    End Sub
  Partial Private Sub UpdateUsuario(instance As Usuario)
    End Sub
  Partial Private Sub DeleteUsuario(instance As Usuario)
    End Sub
  Partial Private Sub InsertParametro(instance As Parametro)
    End Sub
  Partial Private Sub UpdateParametro(instance As Parametro)
    End Sub
  Partial Private Sub DeleteParametro(instance As Parametro)
    End Sub
  Partial Private Sub InsertCliente(instance As Cliente)
    End Sub
  Partial Private Sub UpdateCliente(instance As Cliente)
    End Sub
  Partial Private Sub DeleteCliente(instance As Cliente)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.DataSenalesCaribe.My.MySettings.Default.WR_SenalesCaribeConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Usuarios() As System.Data.Linq.Table(Of Usuario)
		Get
			Return Me.GetTable(Of Usuario)
		End Get
	End Property
	
	Public ReadOnly Property Parametros() As System.Data.Linq.Table(Of Parametro)
		Get
			Return Me.GetTable(Of Parametro)
		End Get
	End Property
	
	Public ReadOnly Property Clientes() As System.Data.Linq.Table(Of Cliente)
		Get
			Return Me.GetTable(Of Cliente)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Usuario")>  _
Partial Public Class Usuario
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _UserName As String
	
	Private _UserPass As String
	
	Private _FullName As String
	
	Private _UserEmail As String
	
	Private _IsLocked As System.Nullable(Of Boolean)
	
	Private _LastLogin_Date As System.Nullable(Of Date)
	
	Private _IsAdmin As System.Nullable(Of Boolean)
	
	Private _NextDatePassword_Change As System.Nullable(Of Date)
	
	Private _Intentos As System.Nullable(Of Integer)
	
	Private _Expired_Date As System.Nullable(Of Date)
	
	Private _IsDeleted As System.Nullable(Of Boolean)
	
	Private _Create_User As String
	
	Private _Create_Date As System.Nullable(Of Date)
	
	Private _Update_User As String
	
	Private _Update_Date As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnUserNameChanging(value As String)
    End Sub
    Partial Private Sub OnUserNameChanged()
    End Sub
    Partial Private Sub OnUserPassChanging(value As String)
    End Sub
    Partial Private Sub OnUserPassChanged()
    End Sub
    Partial Private Sub OnFullNameChanging(value As String)
    End Sub
    Partial Private Sub OnFullNameChanged()
    End Sub
    Partial Private Sub OnUserEmailChanging(value As String)
    End Sub
    Partial Private Sub OnUserEmailChanged()
    End Sub
    Partial Private Sub OnIsLockedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsLockedChanged()
    End Sub
    Partial Private Sub OnLastLogin_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastLogin_DateChanged()
    End Sub
    Partial Private Sub OnIsAdminChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsAdminChanged()
    End Sub
    Partial Private Sub OnNextDatePassword_ChangeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnNextDatePassword_ChangeChanged()
    End Sub
    Partial Private Sub OnIntentosChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIntentosChanged()
    End Sub
    Partial Private Sub OnExpired_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnExpired_DateChanged()
    End Sub
    Partial Private Sub OnIsDeletedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsDeletedChanged()
    End Sub
    Partial Private Sub OnCreate_UserChanging(value As String)
    End Sub
    Partial Private Sub OnCreate_UserChanged()
    End Sub
    Partial Private Sub OnCreate_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreate_DateChanged()
    End Sub
    Partial Private Sub OnUpdate_UserChanging(value As String)
    End Sub
    Partial Private Sub OnUpdate_UserChanged()
    End Sub
    Partial Private Sub OnUpdate_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdate_DateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserName", DbType:="VarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property UserName() As String
		Get
			Return Me._UserName
		End Get
		Set
			If (String.Equals(Me._UserName, value) = false) Then
				Me.OnUserNameChanging(value)
				Me.SendPropertyChanging
				Me._UserName = value
				Me.SendPropertyChanged("UserName")
				Me.OnUserNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserPass", DbType:="VarChar(250)")>  _
	Public Property UserPass() As String
		Get
			Return Me._UserPass
		End Get
		Set
			If (String.Equals(Me._UserPass, value) = false) Then
				Me.OnUserPassChanging(value)
				Me.SendPropertyChanging
				Me._UserPass = value
				Me.SendPropertyChanged("UserPass")
				Me.OnUserPassChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullName", DbType:="VarChar(250)")>  _
	Public Property FullName() As String
		Get
			Return Me._FullName
		End Get
		Set
			If (String.Equals(Me._FullName, value) = false) Then
				Me.OnFullNameChanging(value)
				Me.SendPropertyChanging
				Me._FullName = value
				Me.SendPropertyChanged("FullName")
				Me.OnFullNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserEmail", DbType:="VarChar(250)")>  _
	Public Property UserEmail() As String
		Get
			Return Me._UserEmail
		End Get
		Set
			If (String.Equals(Me._UserEmail, value) = false) Then
				Me.OnUserEmailChanging(value)
				Me.SendPropertyChanging
				Me._UserEmail = value
				Me.SendPropertyChanged("UserEmail")
				Me.OnUserEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsLocked", DbType:="Bit")>  _
	Public Property IsLocked() As System.Nullable(Of Boolean)
		Get
			Return Me._IsLocked
		End Get
		Set
			If (Me._IsLocked.Equals(value) = false) Then
				Me.OnIsLockedChanging(value)
				Me.SendPropertyChanging
				Me._IsLocked = value
				Me.SendPropertyChanged("IsLocked")
				Me.OnIsLockedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastLogin_Date", DbType:="SmallDateTime")>  _
	Public Property LastLogin_Date() As System.Nullable(Of Date)
		Get
			Return Me._LastLogin_Date
		End Get
		Set
			If (Me._LastLogin_Date.Equals(value) = false) Then
				Me.OnLastLogin_DateChanging(value)
				Me.SendPropertyChanging
				Me._LastLogin_Date = value
				Me.SendPropertyChanged("LastLogin_Date")
				Me.OnLastLogin_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsAdmin", DbType:="Bit")>  _
	Public Property IsAdmin() As System.Nullable(Of Boolean)
		Get
			Return Me._IsAdmin
		End Get
		Set
			If (Me._IsAdmin.Equals(value) = false) Then
				Me.OnIsAdminChanging(value)
				Me.SendPropertyChanging
				Me._IsAdmin = value
				Me.SendPropertyChanged("IsAdmin")
				Me.OnIsAdminChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NextDatePassword_Change", DbType:="SmallDateTime")>  _
	Public Property NextDatePassword_Change() As System.Nullable(Of Date)
		Get
			Return Me._NextDatePassword_Change
		End Get
		Set
			If (Me._NextDatePassword_Change.Equals(value) = false) Then
				Me.OnNextDatePassword_ChangeChanging(value)
				Me.SendPropertyChanging
				Me._NextDatePassword_Change = value
				Me.SendPropertyChanged("NextDatePassword_Change")
				Me.OnNextDatePassword_ChangeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Intentos", DbType:="Int")>  _
	Public Property Intentos() As System.Nullable(Of Integer)
		Get
			Return Me._Intentos
		End Get
		Set
			If (Me._Intentos.Equals(value) = false) Then
				Me.OnIntentosChanging(value)
				Me.SendPropertyChanging
				Me._Intentos = value
				Me.SendPropertyChanged("Intentos")
				Me.OnIntentosChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expired_Date", DbType:="SmallDateTime")>  _
	Public Property Expired_Date() As System.Nullable(Of Date)
		Get
			Return Me._Expired_Date
		End Get
		Set
			If (Me._Expired_Date.Equals(value) = false) Then
				Me.OnExpired_DateChanging(value)
				Me.SendPropertyChanging
				Me._Expired_Date = value
				Me.SendPropertyChanged("Expired_Date")
				Me.OnExpired_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsDeleted", DbType:="Bit")>  _
	Public Property IsDeleted() As System.Nullable(Of Boolean)
		Get
			Return Me._IsDeleted
		End Get
		Set
			If (Me._IsDeleted.Equals(value) = false) Then
				Me.OnIsDeletedChanging(value)
				Me.SendPropertyChanging
				Me._IsDeleted = value
				Me.SendPropertyChanged("IsDeleted")
				Me.OnIsDeletedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_User", DbType:="VarChar(50)")>  _
	Public Property Create_User() As String
		Get
			Return Me._Create_User
		End Get
		Set
			If (String.Equals(Me._Create_User, value) = false) Then
				Me.OnCreate_UserChanging(value)
				Me.SendPropertyChanging
				Me._Create_User = value
				Me.SendPropertyChanged("Create_User")
				Me.OnCreate_UserChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_Date", DbType:="SmallDateTime")>  _
	Public Property Create_Date() As System.Nullable(Of Date)
		Get
			Return Me._Create_Date
		End Get
		Set
			If (Me._Create_Date.Equals(value) = false) Then
				Me.OnCreate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Create_Date = value
				Me.SendPropertyChanged("Create_Date")
				Me.OnCreate_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Update_User", DbType:="VarChar(50)")>  _
	Public Property Update_User() As String
		Get
			Return Me._Update_User
		End Get
		Set
			If (String.Equals(Me._Update_User, value) = false) Then
				Me.OnUpdate_UserChanging(value)
				Me.SendPropertyChanging
				Me._Update_User = value
				Me.SendPropertyChanged("Update_User")
				Me.OnUpdate_UserChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Update_Date", DbType:="SmallDateTime")>  _
	Public Property Update_Date() As System.Nullable(Of Date)
		Get
			Return Me._Update_Date
		End Get
		Set
			If (Me._Update_Date.Equals(value) = false) Then
				Me.OnUpdate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Update_Date = value
				Me.SendPropertyChanged("Update_Date")
				Me.OnUpdate_DateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Parametros")>  _
Partial Public Class Parametro
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDParametro As Integer
	
	Private _Descripcion As String
	
	Private _IDGroup As Integer
	
	Private _IDParent As System.Nullable(Of Integer)
	
	Private _OrderBy As System.Nullable(Of Integer)
	
	Private _CustomString As String
	
	Private _CustomInt1 As System.Nullable(Of Integer)
	
	Private _CustomInt2 As System.Nullable(Of Integer)
	
	Private _IsDeleted As Boolean
	
	Private _Create_User As String
	
	Private _Create_Date As Date
	
	Private _Update_User As String
	
	Private _Update_Date As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDParametroChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDParametroChanged()
    End Sub
    Partial Private Sub OnDescripcionChanging(value As String)
    End Sub
    Partial Private Sub OnDescripcionChanged()
    End Sub
    Partial Private Sub OnIDGroupChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDGroupChanged()
    End Sub
    Partial Private Sub OnIDParentChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIDParentChanged()
    End Sub
    Partial Private Sub OnOrderByChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnOrderByChanged()
    End Sub
    Partial Private Sub OnCustomStringChanging(value As String)
    End Sub
    Partial Private Sub OnCustomStringChanged()
    End Sub
    Partial Private Sub OnCustomInt1Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCustomInt1Changed()
    End Sub
    Partial Private Sub OnCustomInt2Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCustomInt2Changed()
    End Sub
    Partial Private Sub OnIsDeletedChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsDeletedChanged()
    End Sub
    Partial Private Sub OnCreate_UserChanging(value As String)
    End Sub
    Partial Private Sub OnCreate_UserChanged()
    End Sub
    Partial Private Sub OnCreate_DateChanging(value As Date)
    End Sub
    Partial Private Sub OnCreate_DateChanged()
    End Sub
    Partial Private Sub OnUpdate_UserChanging(value As String)
    End Sub
    Partial Private Sub OnUpdate_UserChanged()
    End Sub
    Partial Private Sub OnUpdate_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdate_DateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDParametro", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDParametro() As Integer
		Get
			Return Me._IDParametro
		End Get
		Set
			If ((Me._IDParametro = value)  _
						= false) Then
				Me.OnIDParametroChanging(value)
				Me.SendPropertyChanging
				Me._IDParametro = value
				Me.SendPropertyChanged("IDParametro")
				Me.OnIDParametroChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Descripcion", DbType:="VarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property Descripcion() As String
		Get
			Return Me._Descripcion
		End Get
		Set
			If (String.Equals(Me._Descripcion, value) = false) Then
				Me.OnDescripcionChanging(value)
				Me.SendPropertyChanging
				Me._Descripcion = value
				Me.SendPropertyChanged("Descripcion")
				Me.OnDescripcionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDGroup", DbType:="Int NOT NULL")>  _
	Public Property IDGroup() As Integer
		Get
			Return Me._IDGroup
		End Get
		Set
			If ((Me._IDGroup = value)  _
						= false) Then
				Me.OnIDGroupChanging(value)
				Me.SendPropertyChanging
				Me._IDGroup = value
				Me.SendPropertyChanged("IDGroup")
				Me.OnIDGroupChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDParent", DbType:="Int")>  _
	Public Property IDParent() As System.Nullable(Of Integer)
		Get
			Return Me._IDParent
		End Get
		Set
			If (Me._IDParent.Equals(value) = false) Then
				Me.OnIDParentChanging(value)
				Me.SendPropertyChanging
				Me._IDParent = value
				Me.SendPropertyChanged("IDParent")
				Me.OnIDParentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderBy", DbType:="Int")>  _
	Public Property OrderBy() As System.Nullable(Of Integer)
		Get
			Return Me._OrderBy
		End Get
		Set
			If (Me._OrderBy.Equals(value) = false) Then
				Me.OnOrderByChanging(value)
				Me.SendPropertyChanging
				Me._OrderBy = value
				Me.SendPropertyChanged("OrderBy")
				Me.OnOrderByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomString", DbType:="VarChar(100)")>  _
	Public Property CustomString() As String
		Get
			Return Me._CustomString
		End Get
		Set
			If (String.Equals(Me._CustomString, value) = false) Then
				Me.OnCustomStringChanging(value)
				Me.SendPropertyChanging
				Me._CustomString = value
				Me.SendPropertyChanged("CustomString")
				Me.OnCustomStringChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomInt1", DbType:="Int")>  _
	Public Property CustomInt1() As System.Nullable(Of Integer)
		Get
			Return Me._CustomInt1
		End Get
		Set
			If (Me._CustomInt1.Equals(value) = false) Then
				Me.OnCustomInt1Changing(value)
				Me.SendPropertyChanging
				Me._CustomInt1 = value
				Me.SendPropertyChanged("CustomInt1")
				Me.OnCustomInt1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomInt2", DbType:="Int")>  _
	Public Property CustomInt2() As System.Nullable(Of Integer)
		Get
			Return Me._CustomInt2
		End Get
		Set
			If (Me._CustomInt2.Equals(value) = false) Then
				Me.OnCustomInt2Changing(value)
				Me.SendPropertyChanging
				Me._CustomInt2 = value
				Me.SendPropertyChanged("CustomInt2")
				Me.OnCustomInt2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsDeleted", DbType:="Bit NOT NULL")>  _
	Public Property IsDeleted() As Boolean
		Get
			Return Me._IsDeleted
		End Get
		Set
			If ((Me._IsDeleted = value)  _
						= false) Then
				Me.OnIsDeletedChanging(value)
				Me.SendPropertyChanging
				Me._IsDeleted = value
				Me.SendPropertyChanged("IsDeleted")
				Me.OnIsDeletedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_User", DbType:="VarChar(50)")>  _
	Public Property Create_User() As String
		Get
			Return Me._Create_User
		End Get
		Set
			If (String.Equals(Me._Create_User, value) = false) Then
				Me.OnCreate_UserChanging(value)
				Me.SendPropertyChanging
				Me._Create_User = value
				Me.SendPropertyChanged("Create_User")
				Me.OnCreate_UserChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_Date", DbType:="SmallDateTime NOT NULL")>  _
	Public Property Create_Date() As Date
		Get
			Return Me._Create_Date
		End Get
		Set
			If ((Me._Create_Date = value)  _
						= false) Then
				Me.OnCreate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Create_Date = value
				Me.SendPropertyChanged("Create_Date")
				Me.OnCreate_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Update_User", DbType:="VarChar(50)")>  _
	Public Property Update_User() As String
		Get
			Return Me._Update_User
		End Get
		Set
			If (String.Equals(Me._Update_User, value) = false) Then
				Me.OnUpdate_UserChanging(value)
				Me.SendPropertyChanging
				Me._Update_User = value
				Me.SendPropertyChanged("Update_User")
				Me.OnUpdate_UserChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Update_Date", DbType:="SmallDateTime")>  _
	Public Property Update_Date() As System.Nullable(Of Date)
		Get
			Return Me._Update_Date
		End Get
		Set
			If (Me._Update_Date.Equals(value) = false) Then
				Me.OnUpdate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Update_Date = value
				Me.SendPropertyChanged("Update_Date")
				Me.OnUpdate_DateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Cliente")>  _
Partial Public Class Cliente
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDCliente As Integer
	
	Private _pTipo_Cliente As System.Nullable(Of Integer)
	
	Private _Nombre As String
	
	Private _Apellido As String
	
	Private _Telefono As String
	
	Private _Celular As String
	
	Private _Correo_Electronico As String
	
	Private _Fecha_Nacimiento As System.Nullable(Of Date)
	
	Private _pSexo As System.Nullable(Of Integer)
	
	Private _pEstadoCivil As System.Nullable(Of Integer)
	
	Private _Create_User As String
	
	Private _Create_Date As Date
	
	Private _Update_User As String
	
	Private _Update_Date As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDClienteChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDClienteChanged()
    End Sub
    Partial Private Sub OnpTipo_ClienteChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnpTipo_ClienteChanged()
    End Sub
    Partial Private Sub OnNombreChanging(value As String)
    End Sub
    Partial Private Sub OnNombreChanged()
    End Sub
    Partial Private Sub OnApellidoChanging(value As String)
    End Sub
    Partial Private Sub OnApellidoChanged()
    End Sub
    Partial Private Sub OnTelefonoChanging(value As String)
    End Sub
    Partial Private Sub OnTelefonoChanged()
    End Sub
    Partial Private Sub OnCelularChanging(value As String)
    End Sub
    Partial Private Sub OnCelularChanged()
    End Sub
    Partial Private Sub OnCorreo_ElectronicoChanging(value As String)
    End Sub
    Partial Private Sub OnCorreo_ElectronicoChanged()
    End Sub
    Partial Private Sub OnFecha_NacimientoChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFecha_NacimientoChanged()
    End Sub
    Partial Private Sub OnpSexoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnpSexoChanged()
    End Sub
    Partial Private Sub OnpEstadoCivilChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnpEstadoCivilChanged()
    End Sub
    Partial Private Sub OnCreate_UserChanging(value As String)
    End Sub
    Partial Private Sub OnCreate_UserChanged()
    End Sub
    Partial Private Sub OnCreate_DateChanging(value As Date)
    End Sub
    Partial Private Sub OnCreate_DateChanged()
    End Sub
    Partial Private Sub OnUpdate_UserChanging(value As String)
    End Sub
    Partial Private Sub OnUpdate_UserChanged()
    End Sub
    Partial Private Sub OnUpdate_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdate_DateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCliente", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDCliente() As Integer
		Get
			Return Me._IDCliente
		End Get
		Set
			If ((Me._IDCliente = value)  _
						= false) Then
				Me.OnIDClienteChanging(value)
				Me.SendPropertyChanging
				Me._IDCliente = value
				Me.SendPropertyChanged("IDCliente")
				Me.OnIDClienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pTipo_Cliente", DbType:="Int")>  _
	Public Property pTipo_Cliente() As System.Nullable(Of Integer)
		Get
			Return Me._pTipo_Cliente
		End Get
		Set
			If (Me._pTipo_Cliente.Equals(value) = false) Then
				Me.OnpTipo_ClienteChanging(value)
				Me.SendPropertyChanging
				Me._pTipo_Cliente = value
				Me.SendPropertyChanged("pTipo_Cliente")
				Me.OnpTipo_ClienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nombre", DbType:="VarChar(50)")>  _
	Public Property Nombre() As String
		Get
			Return Me._Nombre
		End Get
		Set
			If (String.Equals(Me._Nombre, value) = false) Then
				Me.OnNombreChanging(value)
				Me.SendPropertyChanging
				Me._Nombre = value
				Me.SendPropertyChanged("Nombre")
				Me.OnNombreChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Apellido", DbType:="VarChar(50)")>  _
	Public Property Apellido() As String
		Get
			Return Me._Apellido
		End Get
		Set
			If (String.Equals(Me._Apellido, value) = false) Then
				Me.OnApellidoChanging(value)
				Me.SendPropertyChanging
				Me._Apellido = value
				Me.SendPropertyChanged("Apellido")
				Me.OnApellidoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Telefono", DbType:="VarChar(50)")>  _
	Public Property Telefono() As String
		Get
			Return Me._Telefono
		End Get
		Set
			If (String.Equals(Me._Telefono, value) = false) Then
				Me.OnTelefonoChanging(value)
				Me.SendPropertyChanging
				Me._Telefono = value
				Me.SendPropertyChanged("Telefono")
				Me.OnTelefonoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Celular", DbType:="VarChar(50)")>  _
	Public Property Celular() As String
		Get
			Return Me._Celular
		End Get
		Set
			If (String.Equals(Me._Celular, value) = false) Then
				Me.OnCelularChanging(value)
				Me.SendPropertyChanging
				Me._Celular = value
				Me.SendPropertyChanged("Celular")
				Me.OnCelularChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Correo_Electronico", DbType:="VarChar(150)")>  _
	Public Property Correo_Electronico() As String
		Get
			Return Me._Correo_Electronico
		End Get
		Set
			If (String.Equals(Me._Correo_Electronico, value) = false) Then
				Me.OnCorreo_ElectronicoChanging(value)
				Me.SendPropertyChanging
				Me._Correo_Electronico = value
				Me.SendPropertyChanged("Correo_Electronico")
				Me.OnCorreo_ElectronicoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fecha_Nacimiento", DbType:="SmallDateTime")>  _
	Public Property Fecha_Nacimiento() As System.Nullable(Of Date)
		Get
			Return Me._Fecha_Nacimiento
		End Get
		Set
			If (Me._Fecha_Nacimiento.Equals(value) = false) Then
				Me.OnFecha_NacimientoChanging(value)
				Me.SendPropertyChanging
				Me._Fecha_Nacimiento = value
				Me.SendPropertyChanged("Fecha_Nacimiento")
				Me.OnFecha_NacimientoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pSexo", DbType:="Int")>  _
	Public Property pSexo() As System.Nullable(Of Integer)
		Get
			Return Me._pSexo
		End Get
		Set
			If (Me._pSexo.Equals(value) = false) Then
				Me.OnpSexoChanging(value)
				Me.SendPropertyChanging
				Me._pSexo = value
				Me.SendPropertyChanged("pSexo")
				Me.OnpSexoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pEstadoCivil", DbType:="Int")>  _
	Public Property pEstadoCivil() As System.Nullable(Of Integer)
		Get
			Return Me._pEstadoCivil
		End Get
		Set
			If (Me._pEstadoCivil.Equals(value) = false) Then
				Me.OnpEstadoCivilChanging(value)
				Me.SendPropertyChanging
				Me._pEstadoCivil = value
				Me.SendPropertyChanged("pEstadoCivil")
				Me.OnpEstadoCivilChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_User", DbType:="VarChar(150)")>  _
	Public Property Create_User() As String
		Get
			Return Me._Create_User
		End Get
		Set
			If (String.Equals(Me._Create_User, value) = false) Then
				Me.OnCreate_UserChanging(value)
				Me.SendPropertyChanging
				Me._Create_User = value
				Me.SendPropertyChanged("Create_User")
				Me.OnCreate_UserChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_Date", DbType:="SmallDateTime NOT NULL")>  _
	Public Property Create_Date() As Date
		Get
			Return Me._Create_Date
		End Get
		Set
			If ((Me._Create_Date = value)  _
						= false) Then
				Me.OnCreate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Create_Date = value
				Me.SendPropertyChanged("Create_Date")
				Me.OnCreate_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Update_User", DbType:="VarChar(150)")>  _
	Public Property Update_User() As String
		Get
			Return Me._Update_User
		End Get
		Set
			If (String.Equals(Me._Update_User, value) = false) Then
				Me.OnUpdate_UserChanging(value)
				Me.SendPropertyChanging
				Me._Update_User = value
				Me.SendPropertyChanged("Update_User")
				Me.OnUpdate_UserChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Update_Date", DbType:="SmallDateTime")>  _
	Public Property Update_Date() As System.Nullable(Of Date)
		Get
			Return Me._Update_Date
		End Get
		Set
			If (Me._Update_Date.Equals(value) = false) Then
				Me.OnUpdate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Update_Date = value
				Me.SendPropertyChanged("Update_Date")
				Me.OnUpdate_DateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
